app.py
from flask import Flask, render_template

import controllers

# Initialize Flask app with the template folder address
app = Flask(__name__, template_folder='templates')

# Register the controllers
app.register_blueprint(controllers.main, url_prefix='/wfsnapnsearch', static_url_path="static")
app.register_blueprint(controllers.recommender, url_prefix='/wfsnapnsearch', static_url_path="static")

# Listen on external IPs
# For us, listen to port 3006 so you can just run 'python app.py' to start the server
if __name__ == '__main__':
    # listen on external IPs
	app.run(host='0.0.0.0', port=3006, debug=True)

controllers/__init__.py
from main import *
from recommender import *

controllers/main.py
from flask import *
import os

main = Blueprint('main', __name__, template_folder='templates')

@main.route('/', methods=['GET', 'POST'])
def main_route():
	validFormats = set(['png', 'jpg', 'bmp', 'gif'])
	# if (request.form.get("op") == "img_search"):
	#   	picFile = request.files.get("pic")
	#   	if picFile:
	#   		filename = picFile.filename
	#   		extension = filename[-3:]
	#   		# make sure the file is of a valid picture format
	#   		if extension.lower() not in validFormats and filename[-4:].lower() not in ['tiff', 'jpeg']:
	#   			abort(404)
	#        	# save the uploaded image so we can send it to the model
	#        	curPath = os.path.dirname(__file__)
	#        	relPath = "static/images"
	#        	imagesFolder = os.path.abspath(os.path.join(curPath, os.pardir, relPath))
	#        	picFile.save(os.path.join(imagesFolder, filename))
	#        	# Send the file to the trained model
	#        	# model.recognize(filename)
	#        	# returns JSON data to search by
	#        	# store into set/list/just use the json object and grab the values for each key maybe
	#        		#call container imageInfo
	#        	#redirectURL = "http://www.wayfair.com/keyword.php?keyword="
	#        	redirectURL = "http://www.wayfair.com/keyword.php?keyword=blue+lamp"
	#        	# redirectURL += str(imageInfo[0]);
	#        	# for attr in imageInfo[1:]:
	#        	# 	redirectURL += ("+" + str(attr))
	#        	print redirectURL
	#        	return redirect(redirectURL)

	return render_template("index.html")

controllers/recommender.py
from flask import *
import os

from neural_network.blackbox import WF_Vision as WFV

recommender = Blueprint('recommender', __name__, template_folder='templates')

@recommender.route('/recommender', methods=['GET', 'POST'])
def rec_route():
	options = { 
        "recommend": False
	}

	return render_template("recommender.html", options=options)

@recommender.route('/recommender/recommendations', methods=['GET', 'POST'])
def rec_rec_route():
	options = { 
        "recommend": True
	}

	validFormats = set(['png', 'jpg', 'bmp', 'gif'])
	baseUrl = "http://www.wayfair.com/keyword.php?keyword="
	locationRecs = {
		"artstudio":["board", "toolbox", "easel", "pencil", "desk", "model", "brush", "bench", "smock", "paint"],
		"bar":["cabinet", "stool", "chair", "rack", "tap", "cart", "table", "mirror", "glassware", "opener", "jigger", "serveware"],
	 	"bathroom":["towel", "mat", "rug", "curtain", "sink", "faucet", "mirror", "shower", "tub", "toilet", "faucet", "bathrobe", "washcloth"],
	  	"bedroom":["bed", "headboard", "nightstand", "dresser", "armoire", "pillow", "bench", "comforter", "blanket", "sheet", "quilt", "lamp", "mirror", "rug", "clock", "curtain"],
	   	"children_room":["bed", "lamp", "rug", "light", "nightstand", "bookcase", "chair", "table", "bin", "toy", "tent"],
	    "classroom":["table", "desk", "chair", "board", "screen", "podium", "organizer", "bookcase", "cart", "stand", "cubby", "shelf"],
	    "dining_room":["table", "chair", "cabinet", "sideboard", "buffet", "stool", "bench", "chandelier", "cart", "art", "mirror", "candle", "tableware", "napkin", "vase", "coaster", "shaker", "ramekin", "cruet"],
	    "gameroom":["table", "chair", "pool", "arcade", "sign", "dart", "stool", "couch", "rug", "speaker"],
	    "garage":["rack", "shelf", "cabinet", "bin", "box", "workbench", "shed", "pegboard", "slatwall", "holder", "mat", "bag", "organizer"],
    	"kitchen":["cutlery", "board", "spatula", "strainer", "peeler", "grater", "bakeware", "toaster", "machine", "appliance", "blender", "cookware", "rack", "can", "sink", "light", "fan", "island"],
	    "livingroom":["chair", "table", "couch", "stand", "curtain", "rug", "pillow", "mirror", "ottoman", "lamp", "vase", "plant"],
	    "meeting_room":[], #redirect to office
	    "office":["table", "chair", "desk", "bookcase", "cabinet", "office", "mat", "lamp", "globe", "safe", "organizer"],
	    "restaurant":[]
	}
	if (request.form.get("op") == "img_search"):
	  	picFile = request.files.get("pic")
	  	if picFile:
	  		filename = picFile.filename
	  		extension = filename[-3:]
	  		# make sure the file is of a valid picture format
	  		if extension.lower() not in validFormats and filename[-4:].lower() not in ['tiff', 'jpeg']:
	  			abort(404)
	       	# save the uploaded image so we can send it to the model
	       	curPath = os.path.dirname(__file__)
	       	relPath = "static/image"
	       	imagesFolder = os.path.abspath(os.path.join(curPath, os.pardir, relPath))
	       	picFile.save(os.path.join(imagesFolder, "target_image.jpg"))
	       	# Send the file to the trained model
	       	WFModel = WFV("static/image")
	       	# List of possible locations recognized - first one has the highest accuracy
	       	locList = WFModel.recognize_scene()
	       	#locList = ["children_room", "bedroom", "gameroom", "testing"] #testing
	       	loc = locList[0]
	       	# objects recognized in the photo
	       	imgObjects = WFModel.recognize_objects()
	       	#imgObjects = ["bed", "table"] #testing
	       	# Look in locationRecs[loc] for recommended items
	       	if loc == "children_room":
	       		locName = "kids"
	       	elif loc == "dining_room":
	       		locName = "dining room"
	       	elif loc == "livingroom":
	       		locName = "living room"
	       	elif loc == "meeting_room":
	       		loc = "office"
	       		locName = "office"
	       	elif loc == "restaurant":
	       		loc = "dining_room"
	       		locName = "dining room"
	       	else:
	       		locName = loc

	       	# store into recList a tuple (recommended item type (without location type), rec url)
	       	recList = []
	       	ownedObjs = []
	       	for rec in locationRecs[loc]:
	       		# don't include overlap with imgObjects
	       		if (rec not in imgObjects):
	       			recList.append((rec, baseUrl + locName + "+" + rec))
	       		else: #add them to items you already have
	       			ownedObjs.append(rec)
	       	return render_template("recommender.html", options=options, locName=locName, recList=recList, ownedObjs=ownedObjs, otherLocPos=locList[1:])
	       		

neural_network/__init__.py
from blackbox import *

templates/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
<head>
	<title>WFSnapNSearch</title>
	<!--Import Google Icon Font-->
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="{{url_for('static', filename='css/materialize.min.css')}}" media="screen,projection"/>
    <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}"/>

    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body>
	<div class="container" >
    {% block content %}{% endblock %}
	</div>
	<!--Import jQuery before materialize.js-->
  <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script type="text/javascript" src="{{url_for('static', filename='js/materialize.min.js')}}"></script>
  <script type="text/javascript" src="{{url_for('static', filename='js/main.js')}}"></script>
</body>

</html>

templates/index.html
{% extends "base.html" %}
{% block content %}
  <nav>
    <div class="nav-wrapper purple lighten-1">
      <div class="col s12">
        <a class="breadcrumb"><i class="material-icons" style="padding-left:10px">home</i></a>
        <a class="breadcrumb">WF Snap N Search</a>
      </div>
    </div>
  </nav>

  <table>
  <tr>
  	<!--  -->
      <!-- add a photo action, need to get the photo uploaded -->
      <form action="{{url_for('main.main_route')}}" method="POST" enctype=multipart/form-data>
        <input type="hidden" name="op" value="img_search">
        <div class="file-field input-field">
      		<div class="btn blue-grey lighten-1">
        		<span>Select Photo <i class="material-icons">aspect_ratio</i></span>
        		<input type="file" name="pic" id="file_input" onchange="readURL(this)";>
      		</div>
      		<div class="file-path-wrapper">
        		<input class="file-path validate" type="text" placeholder="Select The Image You Want To Search With">
      		</div>
      		<div style="visibility: hidden" id="image_pic">
      			<img id="simg" src="#" />
      		</div>
    	</div>
    	<td><input disabled class="btn disabled" style="font-weight:normal" type="submit" value="Search" id="file_submit"><i class="material-icons">not_interested</i></td>
      </form>
  </tr>
  <tr>
  	<form action="{{url_for('recommender.rec_route')}}">
  		 <button class="waves-effect waves-light btn" type="submit">Check Out Our Recommender</button>
  	</form>
  </tr>
  </table>

  <script>
		function readURL(input) {
	    	if (input.files && input.files[0]) {
	            var reader = new FileReader();
	            reader.onload = function (e) {
	                $('#simg')
	                    .attr('src', e.target.result)
	            };
	            document.getElementById('image_pic').style.visibility = "";
	            reader.readAsDataURL(input.files[0]);
	        }
	    }
  </script>
{% endblock %}

templates/recommender.html
{% extends "base.html" %}
{% block content %}
  <nav>
    <div class="nav-wrapper purple lighten-1">
      <div class="col s12">
        <a class="breadcrumb"><i class="material-icons" style="padding-left:10px">home</i></a>
        <a href="{{url_for('main.main_route')}}" class="breadcrumb">WF Snap N Search</a>
        {% if options.recommend %}
          <a href="{{url_for('recommender.rec_route')}}" class="breadcrumb">Recommender</a>
          <a class="breadcrumb">Recommendations</a>
        {% else %}
          <a class="breadcrumb">Recommender</a>
        {% endif %}
      </div>
    </div>
  </nav>

  {% if options.recommend %}
    <table>
      <p class="flow-text"> Recommended for {{locName}} {% if locName == "kids" %} room {% endif %}: </p>
      {% if ownedObjs %}
        <p class="flow-text"> We noticed you already have a(n): </p>
        <tr>
          {% for obj in ownedObjs %}
            <p style="border: 2px; margin: 10px;" class=chip>{{locname}} {{obj}}</p>
          {% endfor %}
        </tr>
        {% if recList %}
          <p class="flow-text"> Why not check these other {{locName}} {% if locName == "kids" %} room {% endif %} items out: </p>
        {% endif %}
      {% endif %}
      <tr>
        {% for rec in recList %}
          <p style="border: 2px; margin: 10px;" class=chip><a href="{{rec[1]}}"> {{locName}} {{rec[0]}} </a></p>
        {% endfor %}
      </tr>
    
    <p>
      <form action="{{url_for('recommender.rec_route')}}" id="return_to_rec_form">
        <button class="waves-effect waves-light btn blue-grey lighten-1" type="submit" form="return_to_rec_form">Return To Recommender</button>
      </form>
    </p>

    <p class="flow-text"> Our system is not always correct. Here are some other possibilities: </p>
    <tr>
      {% for loc in otherLocPos %}
        <p style="border: 2px; margin: 10px;" class=chip> {{loc}} {% if loc == "kids" %} room {% endif %} </p>
      {% endfor %}
    </tr>
    </table>
  {% else %}
    <table>
    <tr>
        <!-- add a photo action, need to get the photo uploaded -->
        <form action="{{url_for('recommender.rec_rec_route')}}" method="POST" enctype=multipart/form-data id="get_rec_form">
          <input type="hidden" name="op" value="img_search">
          <div class="file-field input-field">
        		<div class="waves-effect waves-light btn blue-grey lighten-1">
          		<span>Select Photo <i class="material-icons">aspect_ratio</i></span>
          		<input type="file" name="pic" id="file_input" onchange="readURL(this)";>
        		</div>
        		<div class="file-path-wrapper">
          		<input class="file-path validate" type="text" placeholder="Select The Image You Want To Search With">
        		</div>
        		<div style="visibility: hidden" id="image_pic">
        			<img id="simg" src="#" />
        		</div>
      	</div>
      	<!-- <td><input type="submit" value="Get Recommendations" id="file_submit" onclick="showLoaders()";></td> -->
            <td> <button class="waves-effect waves-light btn blue-grey lighten-1" type="submit" form="get_rec_form" id="file_submit" onclick="showCircleLoader()";>Get Recommendations</td>
        </form>
    </tr>
    </table>

    <div id="loading_section">
      <div id="pic_ready_bar"> </div>
      <div id="loading_circles"> </div>
    </div>
  {% endif %}

  <script>
		function showPicReady() {
      document.getElementById('pic_ready_bar').innerHTML =
       '<div class="progress"> <div class="indeterminate"></div></div>';
     }
    function showCircleLoader() {
      document.getElementById('loading_circles').innerHTML = '<div class="preloader-wrapper big active"><div class="spinner-layer spinner-blue"><div class="circle-clipper left"><div class="circle"></div></div><div class="gap-patch"><div class="circle"></div></div><div class="circle-clipper right"><div class="circle"></div></div></div><div class="spinner-layer spinner-red"><div class="circle-clipper left"><div class="circle"></div></div><div class="gap-patch"><div class="circle"></div></div><div class="circle-clipper right"><div class="circle"></div></div></div><div class="spinner-layer spinner-yellow"><div class="circle-clipper left"><div class="circle"></div></div><div class="gap-patch"><div class="circle"></div></div><div class="circle-clipper right"><div class="circle"></div></div></div><div class="spinner-layer spinner-green"><div class="circle-clipper left"><div class="circle"></div></div><div class="gap-patch"><div class="circle"></div></div><div class="circle-clipper right"><div class="circle"></div></div></div></div>';
    }

    function readURL(input) {
	    	if (input.files && input.files[0]) {
	            var reader = new FileReader();
	            reader.onload = function (e) {
	                $('#simg')
	                    .attr('src', e.target.result)
                      .width(227)
                      .height(227)

	            };
	            document.getElementById('image_pic').style.visibility = "";
              showPicReady();
	            reader.readAsDataURL(input.files[0]);
	        }
	    }

  </script>

{% endblock %}